# Generated by Django 3.1.7 on 2021-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=1024, verbose_name='Заголовок')),
                ('seo_keywords', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова страницы')),
                ('seo_description', models.CharField(blank=True, max_length=1024, verbose_name='Мета описание')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('link_name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('link_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['order'],
            },
        ),
    ]
