# Generated by Django 3.1.7 on 2021-04-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link_name',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прайс'),
        ),
        migrations.AddField(
            model_name='service',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликованно'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='PriceServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
            ],
        ),
    ]
