# Generated by Django 3.1.7 on 2021-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210412_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликованно'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link_name',
            field=models.CharField(blank=True, default='Подробнее', max_length=255, null=True, verbose_name='Название кнопки'),
        ),
    ]
