# Generated by Django 3.1.7 on 2021-04-12 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210412_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Созданно')),
                ('seo_title', models.CharField(max_length=1024, verbose_name='Заголовок')),
                ('seo_keywords', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова страницы')),
                ('seo_description', models.CharField(blank=True, max_length=1024, verbose_name='Мета описание')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Созданно'),
            preserve_default=False,
        ),
    ]
