# Generated by Django 3.1.7 on 2021-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20210412_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='showprograms',
            options={'ordering': ['date_start'], 'verbose_name': 'Шоу программа', 'verbose_name_plural': 'Шоу программы'},
        ),
    ]
