# Generated by Django 3.1.7 on 2021-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20210412_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['order'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотогалерея'},
        ),
        migrations.AddField(
            model_name='photogallery',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='priceservices',
            name='days',
            field=models.CharField(default='', max_length=100, verbose_name='Дни'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceservices',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прайс'),
        ),
        migrations.AddField(
            model_name='showprograms',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showprograms',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='showprograms',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликованно'),
        ),
    ]
