# Generated by Django 3.1.7 on 2021-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20210412_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default=0, help_text='Минимальный ценник на пример: От 1200 рублей за час', max_length=50, verbose_name='Прайс'),
        ),
    ]
