# Generated by Django 3.1.7 on 2021-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20210412_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceservices',
            name='days',
            field=models.CharField(help_text='Например: пн-чт', max_length=100, verbose_name='Дни'),
        ),
    ]
