# Generated by Django 3.1.7 on 2021-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20210413_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
