# Generated by Django 3.1.7 on 2021-04-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_photoservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoservices',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии в услуге'},
        ),
    ]
