# Generated by Django 3.1.7 on 2021-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20210418_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoservices',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
