# Generated by Django 3.1.7 on 2021-04-19 11:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20210418_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoservices',
            options={'ordering': ['order'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии в услуге'},
        ),
        migrations.AlterModelOptions(
            name='priceservices',
            options={'ordering': ['order'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='photoservices',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='priceservices',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
