# Generated by Django 3.1.7 on 2021-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_auto_20210419_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
