# Generated by Django 3.1.7 on 2021-04-26 18:03

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_auto_20210423_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos', verbose_name='Фото'),
        ),
    ]
