# Generated by Django 3.1.7 on 2021-11-24 18:27

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import tagging_autocomplete.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_value', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_value', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Опубликованно')),
                ('date_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('tags', tagging_autocomplete.models.TagAutocompleteField(blank=True, help_text='Чтобы использовать тег из 2-х и более слов, нужно вставлять в ковычки', max_length=255, verbose_name='Теги для объекта')),
                ('content', tinymce.models.HTMLField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
            managers=[
                ('allobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPageContent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_value', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('modified_value', models.DateTimeField(blank=True, editable=False, verbose_name='Изменено')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Опубликованно')),
                ('date_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('tags', tagging_autocomplete.models.TagAutocompleteField(blank=True, help_text='Чтобы использовать тег из 2-х и более слов, нужно вставлять в ковычки', max_length=255, verbose_name='Теги для объекта')),
                ('content', tinymce.models.HTMLField(verbose_name='Описание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Страница',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_value', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('modified_value', models.DateTimeField(blank=True, editable=False, verbose_name='Изменено')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Опубликованно')),
                ('date_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('tags', tagging_autocomplete.models.TagAutocompleteField(blank=True, help_text='Чтобы использовать тег из 2-х и более слов, нужно вставлять в ковычки', max_length=255, verbose_name='Теги для объекта')),
                ('desc', tinymce.models.HTMLField(verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='н/п')),
                ('date_event', models.DateTimeField(verbose_name='Дата и время мероприятия')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pages.pagecontent')),
            ],
            options={
                'verbose_name': 'historical Мероприятие',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_value', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_value', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Опубликованно')),
                ('date_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('tags', tagging_autocomplete.models.TagAutocompleteField(blank=True, help_text='Чтобы использовать тег из 2-х и более слов, нужно вставлять в ковычки', max_length=255, verbose_name='Теги для объекта')),
                ('desc', tinymce.models.HTMLField(verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='н/п')),
                ('date_event', models.DateTimeField(verbose_name='Дата и время мероприятия')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pagecontent')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['order'],
            },
            managers=[
                ('allobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
